version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    # Increase the version requirements for npm
    # only when required
    versioning-strategy: increase
