name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sbom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: CycloneDX Node.js Generate SBOM
      # You may pin to the exact commit or the version.
      # uses: CycloneDX/gh-node-module-generatebom@b5753d516608ed84f7a40eb19b7687b5828b9b2d
        uses: CycloneDX/gh-python-generate-sbom@v1.0.0
      - name: Upload SBOM
        uses: actions/upload-artifact@v2.3.1
        with:
          # Artifact name
          name: SBOM
          # A file, directory or wildcard pattern that describes what to upload
          # upload-artifact does NOT use working-directory
          path: ./bom.xml
          if-no-files-found: warn
