# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    defaults:
      run:
        working-directory: ./extension
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: extension/package-lock.json
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run test
      env:
        CI: True
    - name: Upload extension
      uses: actions/upload-artifact@v2.3.1
      with:
        # Artifact name
        name: extension
        # A file, directory or wildcard pattern that describes what to upload
        # upload-artifact does NOT use working-directory
        path: ./extension/build/
        if-no-files-found: error
